### PR TITLE
Add contributor info

### PR DESCRIPTION
**Pull request by frankmilliron**
Not sure why, but Github Desktop is not properly pulling. I have to delete and reclone the repo to add new changes.

### CODE REVIEW

**Comment by frankmilliron** [comment]
refork and reclone... that is...

**Comment by frankmilliron** [comment]
I think I need to change to upstream:master before doing the fetch?

**Comment by peterferrie** [comment]
Your origin needs to be the remote repo not the local one.

**Comment by peterferrie** [comment]
I mean 4am's repo, not your own. Pull from 4am's, push to yours, then make
changes and PR.

**Comment by frankmilliron** [comment]
OK. I think I got it. Will try it out once this commit is merged. Thanks for chiming in and merry christmas qkumba!

**Comment by a2-4am** [comment]
Git is the worst version control system except for all the others.

**Comment by frankmilliron** [comment]
hah.
now it's showing "1 commit ahead, 1 commit behind" so I guess I'll just re-fork it every time.

**Comment by peterferrie** [comment]
It happens if you change something after the PR is submitted but before 4am
approves it. It gets complicated at that point.

**Comment by frankmilliron** [comment]
Seems to be doing it every time, even if I don't add anything new. I'll just delete the fork every time. Not a big deal.

**Pull request merged**
